imports:
    - php

build:
    dependencies:
        before:
            - composer global require "fxp/composer-asset-plugin:~1.0.0"
tools:
    external_code_coverage:
        timeout: 2100 # Timeout in seconds.
    # disable copy paste detector and similarity analyzer as they have no real value
    # and a huge bunch of false-positives
    php_sim: false
    php_cpd: false
