language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.0.0"
  - composer install --no-dev
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
script: phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
